/**
 * Which league band a rank falls in — promotion, safe, or relegation.
 *
 * WHY THIS IS A LIB AND NOT A CONST IN THE PAGE
 *
 * These three functions decide what the app TELLS a student will happen to
 * them on Sunday. The authority on what actually happens is the SQL function
 * `close_study_league_week`. If the two disagree, the page tells someone they
 * are safe and the cron relegates them — a wrong number that looks perfectly
 * confident, which is the failure mode this codebase keeps hitting.
 *
 * Living inside league/page.tsx as unexported consts, they could not be
 * tested at all. `league-bands.test.ts` now diffs every rank in every cohort
 * size 1..30 against a signature generated BY THE DATABASE from the SQL's own
 * expressions, so a divergence fails rather than ships.
 *
 * THE SQL, quoted from pg_get_functiondef:
 *
 *   promotion_event = CASE
 *     WHEN r.rank <= GREATEST(1, r.total / 3) THEN 'promoted'
 *     WHEN r.rank >  r.total - GREATEST(1, r.total / 3) THEN 'demoted'
 *     ELSE 'held'
 *   END
 *
 * Two details that are easy to get wrong and are load-bearing:
 *
 *  - `r.total / 3` is INTEGER division in Postgres (total is bigint from
 *    COUNT(*) OVER ()), so it truncates. Math.floor, not Math.round.
 *  - The CASE tests promotion FIRST. In a small cohort the two bands
 *    overlap — at total=4 the zone is 1, so rank 1 is both "<= 1" and
 *    "> 3"... no; but at total=2 the zone is 1 and rank 1 is <= 1 while
 *    rank 2 is > 1, and at total=1 rank 1 is BOTH promoted and demoted by
 *    the raw predicates. Promotion wins because it is tested first.
 *    `bandFor` reproduces that ordering rather than re-deriving it.
 */

export type LeagueBand = 'promote' | 'safe' | 'relegate'

/** Size of the promotion zone. Mirrors GREATEST(1, total / 3). */
export const promoteZoneFor = (memberCount: number) =>
  Math.max(1, Math.floor(memberCount / 3))

/** First rank inside the relegation zone.
 *  SQL says demoted when `rank > total - Z`, i.e. `rank >= total - Z + 1`. */
export const relegateStartFor = (memberCount: number) =>
  memberCount - promoteZoneFor(memberCount) + 1

export function bandFor(rank: number, memberCount: number): LeagueBand {
  // Promotion first — see the ordering note above.
  if (rank <= promoteZoneFor(memberCount)) return 'promote'
  if (rank >= relegateStartFor(memberCount)) return 'relegate'
  return 'safe'
}
