/**
 * Cross-system check: the band the UI PREDICTS must equal the band the
 * database ACTUALLY assigns.
 *
 * SIGNATURE is not hand-written. It was generated by the live database from
 * `close_study_league_week`'s own CASE expressions, on 2026-08-02:
 *
 *   select string_agg(sig, '|' order by total, rank) from (
 *     select total, rank,
 *       case when rank <= greatest(1, total/3) then 'P'
 *            when rank >  total - greatest(1, total/3) then 'R'
 *            else 'S' end as sig
 *     from generate_series(1,30) total, generate_series(1,30) rank
 *     where rank <= total) x;
 *
 * Re-run that query and paste the result if the SQL function ever changes.
 * If this test fails, ONE of the two is wrong and a student is being told
 * the wrong thing about their week — find out which before "fixing" the
 * expected string.
 */
import { bandFor, promoteZoneFor, relegateStartFor } from '../league-bands'

const SIGNATURE =
  'P|P|R|P|S|R|P|S|S|R|P|S|S|S|R|P|P|S|S|R|R|P|P|S|S|S|R|R|P|P|S|S|S|S|R|R|P|P|P|S|S|S|R|R|R|' +
  'P|P|P|S|S|S|S|R|R|R|P|P|P|S|S|S|S|S|R|R|R|P|P|P|P|S|S|S|S|R|R|R|R|P|P|P|P|S|S|S|S|S|R|R|R|R|' +
  'P|P|P|P|S|S|S|S|S|S|R|R|R|R|P|P|P|P|P|S|S|S|S|S|R|R|R|R|R|P|P|P|P|P|S|S|S|S|S|S|R|R|R|R|R|' +
  'P|P|P|P|P|S|S|S|S|S|S|S|R|R|R|R|R|P|P|P|P|P|P|S|S|S|S|S|S|R|R|R|R|R|R|' +
  'P|P|P|P|P|P|S|S|S|S|S|S|S|R|R|R|R|R|R|P|P|P|P|P|P|S|S|S|S|S|S|S|S|R|R|R|R|R|R|' +
  'P|P|P|P|P|P|P|S|S|S|S|S|S|S|R|R|R|R|R|R|R|P|P|P|P|P|P|P|S|S|S|S|S|S|S|S|R|R|R|R|R|R|R|' +
  'P|P|P|P|P|P|P|S|S|S|S|S|S|S|S|S|R|R|R|R|R|R|R|P|P|P|P|P|P|P|P|S|S|S|S|S|S|S|S|R|R|R|R|R|R|R|R|' +
  'P|P|P|P|P|P|P|P|S|S|S|S|S|S|S|S|S|R|R|R|R|R|R|R|R|' +
  'P|P|P|P|P|P|P|P|S|S|S|S|S|S|S|S|S|S|R|R|R|R|R|R|R|R|' +
  'P|P|P|P|P|P|P|P|P|S|S|S|S|S|S|S|S|S|R|R|R|R|R|R|R|R|R|' +
  'P|P|P|P|P|P|P|P|P|S|S|S|S|S|S|S|S|S|S|R|R|R|R|R|R|R|R|R|' +
  'P|P|P|P|P|P|P|P|P|S|S|S|S|S|S|S|S|S|S|S|R|R|R|R|R|R|R|R|R|' +
  'P|P|P|P|P|P|P|P|P|P|S|S|S|S|S|S|S|S|S|S|R|R|R|R|R|R|R|R|R|R'

const LETTER: Record<string, string> = { promote: 'P', safe: 'S', relegate: 'R' }

describe('league bands match close_study_league_week', () => {
  it('agrees with the database on every rank in every cohort size 1..30', () => {
    const sig: string[] = []
    for (let total = 1; total <= 30; total++) {
      for (let rank = 1; rank <= total; rank++) sig.push(LETTER[bandFor(rank, total)]!)
    }
    expect(sig.join('|')).toBe(SIGNATURE)
  })

  it('uses integer division, not rounding', () => {
    // total=8 -> 8/3 = 2 in Postgres, 2.67 rounded would be 3. A rounding
    // bug would silently widen the promotion zone by one student.
    expect(promoteZoneFor(8)).toBe(2)
    expect(promoteZoneFor(11)).toBe(3)
  })

  it('never returns a zone below 1, however small the cohort', () => {
    for (let n = 1; n <= 5; n++) expect(promoteZoneFor(n)).toBeGreaterThanOrEqual(1)
  })

  it('resolves the overlap in favour of promotion, as the SQL CASE does', () => {
    // total=1: rank 1 satisfies BOTH raw predicates (1 <= 1 and 1 > 0).
    // The SQL tests promotion first, so a lone member is promoted, not
    // relegated. Getting this backwards would demote every solo cohort.
    expect(bandFor(1, 1)).toBe('promote')
    expect(relegateStartFor(1)).toBe(1)
  })
})
